name: krishijodd
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.2
  google_fonts: ^4.0.3
  flutter_signin_button: ^2.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_custom_tabs: ^1.0.4
  url_launcher: ^6.1.0
  firebase_core: ^2.5.0
  firebase: ^9.0.3
  auth: ^8.2.0+02
  firebase_auth: ^4.2.6
  google_sign_in: ^5.4.4
  youtube_player_flutter: ^8.1.2
  custom_button: ^0.0.1
  image_picker: ^0.8.6+2
  path_provider: ^2.0.12
  get: ^4.6.5
  cloud_firestore: ^4.3.2
  flutter_speed_dial: ^6.2.0
  dropdown_button2: ^1.9.2
  firebase_database: ^10.0.13
  firebase_storage: ^11.0.13
  file_picker: ^5.2.5
  mailto: ^2.0.0
  lottie: ^2.2.0
  animations: ^2.0.7
  readmore: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/kisan.png
    - assets/images/amazon.png
    - assets/images/avatar.png
    - assets/images/kisan.png
    - assets/images/amazon.png
    - assets/images/avatar.png
    - assets/images/google.png
    - assets/images/hero.png
    - assets/images/post-img.jpg
    - assets/json/resources.json
    - assets/json/productlist.json
    - assets/images/123.png
    - assets/images/google.png
    - assets/images/hero.png
    - assets/images/post-img.jpg
    - assets/json/productlist.json
    - assets/images/123.png
    - assets/lottie/86090-re-fork-farmer.json

    


