// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRA99UCQvZNR4blTGTAmMrmpMRkEzf34M',
    appId: '1:49115974578:web:afe03d12257fdf761272ab',
    messagingSenderId: '49115974578',
    projectId: 'krishijodd---diversion2k23',
    authDomain: 'krishijodd---diversion2k23.firebaseapp.com',
    storageBucket: 'krishijodd---diversion2k23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyMT1D9-jpRYpWCIdPARC3G0kMixYjwYw',
    appId: '1:49115974578:android:0ca27768c4d3b5a31272ab',
    messagingSenderId: '49115974578',
    projectId: 'krishijodd---diversion2k23',
    storageBucket: 'krishijodd---diversion2k23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDF59acf3B0z6-ftoVBOV5RuF-AK2hmXo',
    appId: '1:49115974578:ios:58e86a4f89e8feb51272ab',
    messagingSenderId: '49115974578',
    projectId: 'krishijodd---diversion2k23',
    storageBucket: 'krishijodd---diversion2k23.appspot.com',
    iosClientId:
        '49115974578-gl12ovr99fhncabkr8o9iugcaovibadc.apps.googleusercontent.com',
    iosBundleId: 'com.example.krishijodd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDF59acf3B0z6-ftoVBOV5RuF-AK2hmXo',
    appId: '1:49115974578:ios:58e86a4f89e8feb51272ab',
    messagingSenderId: '49115974578',
    projectId: 'krishijodd---diversion2k23',
    storageBucket: 'krishijodd---diversion2k23.appspot.com',
    iosClientId:
        '49115974578-gl12ovr99fhncabkr8o9iugcaovibadc.apps.googleusercontent.com',
    iosBundleId: 'com.example.krishijodd',
  );
}
